"""Added category and date_added fields

Revision ID: f992baa6ba38
Revises: 18059dc47c14
Create Date: 2025-02-13 14:58:10.961245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f992baa6ba38'
down_revision = '18059dc47c14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', sa.DateTime(), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('date_added', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('date_added')
        batch_op.drop_column('category')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('date_added')

    # ### end Alembic commands ###
