apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: gcr.io/strapi-385510/flask-app:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: app-config
        volumeMounts:
        - name: gcs-credentials
          mountPath: "/app/strapi-385510-04a56795d885.json"
          subPath: "credentials.json"
        resources:
          requests:
            cpu: "250m"  # Request 250 millicores of CPU
            memory: "512Mi"  # Request 512 MiB of memory
          limits:
            cpu: "500m"  # Limit to 500 millicores of CPU
            memory: "1Gi"  # Limit to 1 GiB of memory
      volumes:
      - name: gcs-credentials
        secret:
          secretName: gcs-credentials